on:
  push:
    branches:
      - master
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing"
        run: ls 
      - uses: actions/checkout@v3
      - name: "Testing after"
        run: ls -a